export const FETCH_PARKS_REQUEST = 'FETCH_PARKS_REQUEST';
export const FETCH_PARKS_SUCCESS = 'FETCH_PARKS_SUCCESS';
export const FETCH_PARKS_ERROR = 'FETCH_PARKS_ERROR';
export const SET_CURRENT_PARK = 'SET_CURRENT_PARK';

export const FETCH_ANIMALS_REQUEST = 'FETCH_ANIMALS_REQUEST';
export const FETCH_ANIMALS_SUCCESS = 'FETCH_ANIMALS_SUCCESS';
export const FETCH_ANIMALS_ERROR = 'FETCH_ANIMALS_ERROR';
export const SET_CURRENT_ANIMAL = 'SET_CURRENT_ANIMAL';

export const FETCH_SIGHTINGS_REQUEST = 'FETCH_SIGHTINGS_REQUEST';
export const FETCH_SIGHTINGS_SUCCESS = 'FETCH_SIGHTINGS_SUCCESS';
export const FETCH_SIGHTINGS_ERROR = 'FETCH_SIGHTINGS_ERROR';

export const SET_USER = 'SET_USER';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const FETCH_USER_LOG_REQUEST = 'FETCH_USER_LOG_REQUEST';
export const FETCH_USER_LOG_SUCCESS = 'FETCH_USER_LOG_SUCCESS';
export const FETCH_USER_LOG_ERROR = 'FETCH_USER_LOG_ERROR';

export const SAVE_SIGHTING_REQUEST = 'SAVE_SIGHTING_REQUEST';
export const SAVE_SIGHTING_ERROR = 'SAVE_SIGHTING_ERROR';
export const SAVE_SIGHTING_SUCCESS = 'SAVE_SIGHTING_SUCCESS';

export const CLEAR_SIGHTINGS = 'CLEAR_SIGHTINGS';
export const REMOVE_SIGHTING = 'REMOVE_SIGHTING';

export const SELECT_RANDOM_SEARCH_MODE = 'SELECT_RANDOM_SEARCH_MODE';
export const SELECT_MAP_NAV_MODE = 'SELECT_MAP_NAV_MODE';

export const SET_SIGHTINGINFO_VISIBILITY = 'SET_SIGHTINGINFO_VISIBILITY';
export const SET_ANIMALINFO_VISIBILITY = 'SET_ANIMALINFO_VISIBILITY';
export const SET_CONFIRMSAVE_VISIBILITY = 'SET_CONFIRMSAVE_VISIBILITY';

export const SET_USER_LOCATION = 'SET_USER_LOCATION';
