export const FETCH_PARKS_REQUEST = 'FETCH_PARKS_REQUEST';
export const FETCH_PARKS_SUCCESS = 'FETCH_PARKS_SUCCESS';
export const FETCH_PARKS_ERROR = 'FETCH_PARKS_ERROR';

export const FETCH_ANIMALS_REQUEST = 'FETCH_ANIMALS_REQUEST';
export const FETCH_ANIMALS_SUCCESS = 'FETCH_ANIMALS_SUCCESS';
export const FETCH_ANIMALS_ERROR = 'FETCH_ANIMALS_ERROR';

export const FETCH_ANIMAL_SIGHTINGS_REQUEST = 'FETCH_ANIMAL_SIGHTINGS_REQUEST';
export const FETCH_ANIMAL_SIGHTINGS_SUCCESS = 'FETCH_ANIMAL_SIGHTINGS_SUCCESS';
export const FETCH_ANIMAL_SIGHTINGS_ERROR = 'FETCH_ANIMAL_SIGHTINGS_SUCCESS';

export const POST_ANIMAL_REQUEST = 'POST_ANIMAL_REQUEST';
export const POST_ANIMAL_SUCCESS = 'POST_ANIMAL_SUCCESS';
export const POST_ANIMAL_ERROR = 'POST_ANIMAL_ERROR';

export const FETCH_RANDOM_SIGHTINGS = 'FETCH_RANDOM_SIGHTINGS';
export const FETCH_RANDOM_SIGHTINGS_SUCCESS = 'FETCH_RANDOM_SIGHTINGS_SUCCESS';
export const FETCH_RANDOM_SIGHTINGS_ERROR = 'FETCH_RANDOM_SIGHTINGS_ERROR';

export const POST_USERINFO_REQUEST = 'POST_USERINFO_REQUEST';
export const POST_USERINFO_SUCCESS = 'POST_USERINFO_SUCCESS';
export const POST_USERINFO_ERROR = 'POST_USERINFO_ERROR';

export const POST_SIGHTING_REQUEST = 'POST_SIGHTING_REQUEST';
export const POST_SIGHTING_SUCCESS = 'POST_SIGHTING_SUCCESS';
export const POST_SIGHTING_ERROR = 'POST_SIGHTING_REQUEST';

export const SET_MAPMODAL_VISIBILITY = 'SET_MAPMODAL_VISIBILITY';
export const SET_SAVEMODAL_VISIBILITY = 'SET_SAVEMODAL_VISIBILITY';
export const SET_ABOUTMODAL_VISIBILITY = 'SET_ABOUTMODAL_VISIBILITY';
export const SET_PARKINFOMODAL_VISIBILITY = 'SET_PARKINFOMODAL_VISIBILITY';
